server:
  port: ${port:6061}

#配置eureka实例
eureka:
  instance:
    hostname: localhost
  client:
    #默认值为真，是否需要将自己注册到服务器，集群需要
    register-with-eureka: true
    #是否需要从Eureka服务器获取其他注册服务的信息，集群需要
    fetch-registry: true
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: ${defaultZone:http://localhost:6061/eureka}
#    server:
#      enable-self-preservation: false #禁用保护机制
#      eviction-interval-timer-in-ms: 2000 #服务剔除，默认60秒启动服务剔除，会剔除超过90秒没有发送心跳信号的服务
spring:
  application:
    name: eureka



